# ANTES DE EJECUTAR ESTE SCRIPT, ASEGURATE DE CAMBIAR EN UNO DE LOS STEPS <aws_access_key_id> <aws_secret_access_key> <aws_session_token> POR TUS CREDENCIALES.

aws emr create-cluster \
 --name "Custer Proyecto 3" \
 --log-uri "s3://aws-logs-230637616029-us-east-1/elasticmapreduce" \
 --release-label "emr-7.4.0" \
 --service-role "arn:aws:iam::230637616029:role/EMR_DefaultRole" \
 --unhealthy-node-replacement \
 --ec2-attributes '{"InstanceProfile":"EMR_EC2_DefaultRole","EmrManagedMasterSecurityGroup":"sg-092d64ecb60fc062b","EmrManagedSlaveSecurityGroup":"sg-06354c8dd9d7e3aa7","KeyName":"laboratorio-3-2","SubnetId":"subnet-004529e940a9c7063"}' \
 --applications Name=HCatalog Name=Hadoop Name=Hive Name=Hue Name=JupyterEnterpriseGateway Name=JupyterHub Name=Livy Name=Spark Name=Sqoop Name=Zeppelin Name=ZooKeeper \
 --configurations '[{"Classification":"jupyter-s3-conf","Properties":{"s3.persistence.bucket":"mdcorreah2notebooks","s3.persistence.enabled":"true"}},{"Classification":"hive-site","Properties":{"hive.metastore.client.factory.class":"com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"}},{"Classification":"spark-hive-site","Properties":{"hive.metastore.client.factory.class":"com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"}}]' \
 --instance-groups '[{"InstanceCount":1,"InstanceGroupType":"MASTER","Name":"Primary","InstanceType":"m4.xlarge","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"VolumeType":"gp2","SizeInGB":32},"VolumesPerInstance":2}]}},{"InstanceCount":1,"InstanceGroupType":"CORE","Name":"Core","InstanceType":"m4.xlarge","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"VolumeType":"gp2","SizeInGB":32},"VolumesPerInstance":2}]}},{"InstanceCount":1,"InstanceGroupType":"TASK","Name":"Task - 1","InstanceType":"m4.xlarge","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"VolumeType":"gp2","SizeInGB":32},"VolumesPerInstance":2}]}}]' \
 --steps '[{"Name":"Inicial Modificado","ActionOnFailure":"CANCEL_AND_WAIT","Jar":"s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"=","Args":["s3://covid19bucket-mauricio/scripts/init.sh","bash","-c","aws s3 cp s3://covid19bucket-mauricio/scripts/init.sh . && chmod +x init.sh && ./init.sh"],"Type":"CUSTOM_JAR"},{"Name":"Ingesta modificado","ActionOnFailure":"CANCEL_AND_WAIT","Jar":"s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"=","Args":["s3://covid19bucket-mauricio/scripts/ingesta.sh","bash","-c","aws s3 cp s3://covid19bucket-mauricio/scripts/ingesta.sh . && chmod +x ingesta.sh && ./ingesta.sh"],"Type":"CUSTOM_JAR"},{"Name":"Procesamiento","ActionOnFailure":"CANCEL_AND_WAIT","Jar":"s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"=","Args":["s3://covid19bucket-mauricio/scripts/procesamiento.sh","bash","-c","aws s3 cp s3://covid19bucket-mauricio/scripts/procesamiento.sh . && chmod +x procesamiento.sh && ./procesamiento.sh"],"Type":"CUSTOM_JAR"},{"Name":"credentials","ActionOnFailure":"CONTINUE","Jar":"s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"=","Args":["s3://covid19bucket-mauricio/scripts/credentials.sh","<aws_access_key_id>","<aws_secret_access_key>","<aws_session_token>"],"Type":"CUSTOM_JAR"},{"Name":"creating table 004","ActionOnFailure":"CANCEL_AND_WAIT","Jar":"s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"=","Args":["s3://covid19bucket-mauricio/scripts/creating_table.sh","bash","-c","aws s3 cp s3://covid19bucket-mauricio/scripts/creating_table.sh . && chmod +x creating_table.sh && ./creating_table.sh"],"Type":"CUSTOM_JAR"},{"Name":"Cargar Archivo Creating Full Tables.","ActionOnFailure":"CANCEL_AND_WAIT","Jar":"s3://us-east-1.elasticmapreduce/libs/script-runner/script-runner.jar","Properties":"","Args":["s3://covid19bucket-mauricio/scripts/tables.sh","bash","-c","aws s3 cp s3://covid19bucket-mauricio/scripts/tables.sh . && chmod +x tables.sh && ./tables.sh"],"Type":"CUSTOM_JAR"}]' \
 --auto-scaling-role "arn:aws:iam::230637616029:role/EMR_AutoScaling_DefaultRole" \
 --scale-down-behavior "TERMINATE_AT_TASK_COMPLETION" \
 --region "us-east-1"